import {Fragment} from "react";
import {ArrowRight,Check,Search,ShieldCheck,Users,ChartNoAxesCombined,Target,LayoutGrid} from "lucide-react";
import {Header,BrandCTA,HeroMatchingPreview,FAQAccordion,CreatorPool,CompareToggle,AudienceCTA} from "@/components/site-interactions";
import Link from "@/components/plain-link";
import {BrandLogo} from "@/components/brand-logo";
import {siteConfig} from "@/lib/site-config";
export function Footer(){return <footer className="footer"><div className="wrap"><div className="footer-grid"><div><Link className="brand-home" href="/" aria-label="STEP1NE MATCH 首頁"><BrandLogo footer/></Link><p>AI 精準媒合 × 真人顧問<br/>讓品牌與創作者，找到更好的合作。</p></div><div className="footer-links"><Link href="/#services">品牌合作</Link><Link href="/#ai-matching">AI 精準媒合</Link><Link href="/#workflow">合作流程</Link><Link href="/creators">申請加入創作者網絡</Link><Link href="/#faq">常見問題</Link><Link href="/brand-brief">聯絡顧問</Link></div></div><div className="copyright"><span>© 2026 STEP1NE MATCH. All rights reserved.</span><span>品牌合作媒合平台 · 網站預覽版</span></div></div></footer>}
const capabilities=[{icon:Search,title:"AI 人才探索",text:"從嚴選創作者網絡與可取得的公開資訊，探索符合需求的合作人選。"},{icon:Target,title:"AI 契合度分析",text:"比對品牌、受眾、內容與平台需求，整理值得推薦的原因。"},{icon:ShieldCheck,title:"Creator 數據驗證",text:"結合已提供的 Insights、代表作品與合作紀錄，建立判斷依據。"},{icon:Users,title:"Human Review",text:"AI 協助縮小範圍，最終合作判斷由專業顧問人工審核。"}];
const rings=[{label:"契合度",en:"Relevance",tone:"t-fit",radius:134,offset:0,items:["受眾|契合度","內容|契合度","品牌|合作經驗"]},{label:"影響力",en:"Reach & Resonance",tone:"t-perf",radius:200,offset:60,items:["互動率","觸及|與觀看","成長與|穩定度"]},{label:"可信度",en:"Credibility & Safety",tone:"t-trust",radius:265,offset:20,items:["受眾|真實性","品牌|安全","合作|履約紀錄"]}];
function DimensionOrbit(){return <div className="orbit-wrap"><div className="orbit" role="list" aria-label="創作者九個評估維度">{rings.map(r=><div key={r.label} className="orbit-ring" style={{"--radius":r.radius} as React.CSSProperties}><span className="orbit-path"/>{r.items.map((t,i)=><div key={t} role="listitem" className="orbit-item" style={{"--angle":i*120+r.offset} as React.CSSProperties}><span className={`orbit-pill ${r.tone}`}>{t.split("|").map((w,k)=><Fragment key={k}>{k>0&&<wbr/>}{w}</Fragment>)}</span></div>)}</div>)}<div className="orbit-core">創作者</div></div><div className="orbit-legend">{rings.map(r=><span key={r.label}><i className={r.tone}/>{r.label}<small>{r.en}</small></span>)}</div></div>}
const roleTone:Record<string,string>={"品牌":"brand","AI":"ai","顧問":"advisor","創作者":"creator"};
const flow=[{name:"媒合",steps:[{title:"品牌提交需求",roles:["品牌"],detail:"提供品牌、產品、目標客群、推廣目標、預算與時程。已經有 Brand Deck 或需求文件，可以直接提供，顧問會先整理既有資訊，再確認缺少的內容。"},{title:"AI 媒合與配對",roles:["AI"],detail:"把品牌需求轉成多維度條件，從嚴選創作者網絡與可取得的公開資訊中，比對受眾、內容、平台與歷史合作紀錄，找出候選人選並整理推薦原因。"},{title:"顧問人工審核",roles:["顧問"],detail:"顧問逐一檢查 AI 推薦的人選與資料來源，確認推薦原因是否成立。沒有取得的資料會清楚標示，不把未知當成已驗證。"},{title:"品牌挑選",roles:["品牌"],detail:"品牌檢視顧問整理後的推薦人選與推薦原因，選出想進一步洽談合作的創作者。"}]},{name:"執行",steps:[{title:"策略與執行分析",roles:["AI"],detail:"依品牌需求與選定的人選，由 AI 分析推廣策略與執行方向，整理成一份報告交付給品牌，作為後續邀約與合作執行的依據。"},{title:"Creator 邀約與條件確認",roles:["顧問","創作者"],detail:"依創作者報價、內容形式、發布平台、授權範圍與檔期確認合作條件。顧問整理費用與服務範圍，由品牌確認後再推進。"},{title:"內容與發布管理",roles:["創作者","顧問"],detail:"創作者製作與發布內容，我們以系統化方式統一管理每位創作者的內容與發布時程，顧問逐一追蹤進度，品牌不用自己一個個私訊、一個個記進度。"}]},{name:"成效",steps:[{title:"成效回收",roles:["顧問"],detail:"發布後整理觸及、觀看、互動與可追蹤的點擊等結果。可驗證的範圍，依平台權限、追蹤設定與創作者提供的資料而定。"},{title:"下一波建議",roles:["AI","顧問"],detail:"先由 AI 分析這一波的成效與數據，比較平台分布、創作者表現與內容角度；再由顧問評估分析結果，提出下一波合作建議。合作表現也會回寫，讓下一次媒合不用從零開始。"}]}];
const srcTone:Record<string,string>={"公開資料":"public","創作者提供":"creator","顧問確認":"advisor"};
const dataRows=[["社群帳號與代表作品","經營平台、內容類型、代表作"],["粉絲輪廓","年齡、性別、地區分布"],["內容表現","觀看、互動與近期發文狀況"],["過往業配與報價","合作過的品牌類型、報價區間"]].map(([l,d],i)=>[l,d,["公開資料","創作者提供","公開資料","顧問確認"][i]]);
export default function Home(){return <><Header/><main id="main"><section className="hero"><div className="wrap"><div className="hero-grid"><div><div className="eyebrow">AI-POWERED KOC / KOL MATCHING PLATFORM</div><h1>AI 精準媒合，<br/>找到真正能為品牌<br/><span className="gradient">帶來成果</span>的 KOC / KOL</h1><p className="lead">不只看粉絲數，而是綜合受眾、內容風格、平台表現與歷史合作數據，從人選媒合、合作執行到成效追蹤，一站完成。</p><div className="actions"><BrandCTA/><Link className="btn secondary" href="#workflow">了解合作流程<ArrowRight size={17}/></Link></div><Link className="textlink" href={siteConfig.creatorJoinUrl}>我是 KOC / KOL → 申請加入嚴選創作者網絡</Link></div><HeroMatchingPreview/></div><div className="trust">{[[Target,"AI 精準媒合"],[ShieldCheck,"Creator 數據驗證"],[Users,"真人顧問把關"],[ChartNoAxesCombined,"Campaign 成效追蹤"]].map(([Icon,label])=>{const I=Icon as typeof Target;return <span key={String(label)}><I/>{String(label)}</span>})}</div></div></section>
<section className="section soft"><div className="wrap split"><div><div className="eyebrow">THE PROBLEM</div><h2>粉絲數，<br/>不等於適合度。</h2><p className="lead">找 KOC / KOL，不該只是從粉絲最多的人開始挑。</p><div className="actions"><Link className="btn" href="#ai-matching">看看 AI 如何媒合<ArrowRight size={17}/></Link></div></div><div><CompareToggle/><p className="quote">AI 先找出值得看的那群人，再由專業顧問完成最後判斷。</p></div></div></section>
<section className="section" id="ai-matching"><div className="wrap"><div className="eyebrow">AI CAPABILITIES</div><div className="section-top"><div><h2>不只找得到人，<br/>更要知道「為什麼適合」。</h2><p className="lead">AI 精準媒合，是將品牌需求轉成多維度條件，結合創作者資料與實際合作紀錄，協助顧問更快找出高契合候選人。</p></div><Link className="btn secondary" href="#dimensions">了解媒合維度<ArrowRight size={17}/></Link></div><div className="marquee"><div className="marquee-track">{[0,1].map(copy=>capabilities.map((c,i)=><article className="cap" key={copy+c.title} aria-hidden={copy===1||undefined}><small>0{i+1}</small><span className="icon"><c.icon size={22}/></span><h3>{c.title}</h3><p>{c.text}</p></article>))}</div></div></div></section>
<section className="journey" id="services"><div className="wrap"><div className="section-top"><div><div className="eyebrow">FROM BRIEF TO REAL IMPACT</div><h2>從找人，到合作真正落地。</h2><p className="lead">不是丟一份名單給品牌，而是把 KOC / KOL 合作流程一路往前推進。</p></div><BrandCTA>提交品牌合作需求</BrandCTA></div><div className="duty"><div className="duty-col brand"><div className="duty-label">品牌只要</div><ul>{["提供需求","挑選人選","確認合作條件"].map(t=><li key={t}><span className="duty-dot"/>{t}</li>)}</ul></div><div className="duty-col ours"><div className="duty-label">STEP1NE 負責</div><ul>{["找人與審核","邀約與洽談條件","追蹤內容與發布進度","回收成效與下一波建議"].map(t=><li key={t}><Check size={18}/>{t}</li>)}</ul></div></div></div></section>
<section className="section" id="dimensions"><div className="wrap split"><div><div className="eyebrow">CREATOR INTELLIGENCE PROFILE</div><h2>我們看的，<br/>不只有粉絲數。</h2><p className="lead">每個創作者都有自己的合作輪廓，而不是只剩一個 Followers 數字。</p><p className="quote">受眾是否吻合？內容是否自然？<br/>合作資料是否足以支持推薦？</p></div><DimensionOrbit/></div></section>
<section className="section soft"><div className="wrap split"><div className="verification"><div className="panel-heading"><strong>創作者資料卡</strong><span className="note-inline">每筆標註來源與更新日期</span></div>{dataRows.map(([l,d,tag])=><div className="data-row" key={l}><div><b>{l}</b><span>{d}</span></div><span className={`src src-${srcTone[tag]}`}>{tag}</span></div>)}<div className="src-legend"><span className="src src-none">尚未取得</span><p>沒拿到的資料就直接標示，不用估算的數字補上。</p></div></div><div><div className="eyebrow">CREATOR DATA VERIFICATION</div><h2>公開數字，<br/>只是第一層。</h2><p className="lead">值得推薦的創作者，我們會進一步建立可驗證的合作資料。從代表作品到受眾洞察，把「看起來適合」變成有依據的判斷。</p><p className="quote">沒有取得的資料，就清楚標示。<br/>不把未知，當成已驗證。</p></div></div></section>
<section className="section" id="workflow"><div className="wrap"><div className="eyebrow">COLLABORATION WORKFLOW</div><h2>從媒合到發布，<br/>每一步都有人追。</h2><p className="lead">品牌不用自己一個個私訊、一個個記進度。</p><div className="flow">{flow.map((phase,p)=><div className="flow-phase" key={phase.name}><div className="flow-phase-name"><span>0{p+1}</span>{phase.name}</div><ol className="flow-steps">{phase.steps.map(st=><li key={st.title}><details><summary><h3>{st.title}</h3><div className="flow-roles">{st.roles.map(r=><span key={r} className={`role role-${roleTone[r]}`}>{r}</span>)}</div></summary><p>{st.detail}</p></details></li>)}</ol></div>)}</div></div></section>
<section className="section soft" id="results"><div className="wrap"><div className="eyebrow">CAMPAIGN PERFORMANCE</div><h2>最後看的，不是「找了幾個人」，<br/>而是「做出了什麼結果」。</h2><p className="lead">把分散的數據整理在一起，看見不同人選、平台與內容角度的合作表現。</p><div className="report"><div className="report-card"><div className="report-head"><strong>成效報告</strong><span>每波合作結束後交付</span></div><div className="report-metrics">{[["觸及","151K"],["觀看","18K"],["互動","5K"],["點擊","2K"]].map(([l,n])=><div key={l}><span>{l}</span><strong>{n}</strong></div>)}</div><div className="report-sub">創作者表現比較</div><div className="report-bars">{[["A",82],["B",58],["C",36]].map(([k,w])=><div key={k}><b>{k}</b><em>創作者 {k}</em><span><i style={{width:`${w}%`}}/></span></div>)}</div></div><div className="report-list"><strong>報告裡你會看到</strong><ul>{[[ChartNoAxesCombined,"觸及、觀看、互動與可追蹤點擊"],[Users,"每位創作者的表現比較"],[LayoutGrid,"平台分布與內容角度"],[ArrowRight,"AI 分析＋顧問的下一波建議"]].map(([Icon,t])=>{const I=Icon as typeof Users;return <li key={String(t)}><I size={19}/>{String(t)}</li>})}</ul><p className="note">可追蹤的指標，依平台權限、追蹤設定與創作者提供的資料而定。</p></div></div></div></section>
<section className="section"><div className="wrap split"><div><div className="eyebrow">PERFORMANCE LEARNING LOOP</div><h2>每一次合作，<br/>都讓下一次媒合更準。</h2></div><div><p>創作者的真實合作表現、內容成果與品牌回饋持續回寫，讓下一次媒合不再從零開始。</p><div className="cycle" role="img" aria-label="合作回圈：媒合、合作、成效、回寫，再回到下一次媒合"><ol className="cycle-steps">{["媒合","合作","成效","回寫"].map(t=><li key={t}><span>{t}</span></li>)}</ol><div className="cycle-return"/><p className="cycle-note">回到下一次媒合，資料更完整</p></div></div></div></section>
<section className="section soft"><div className="wrap split"><div><div className="eyebrow">YOUR BRAND, YOUR CREATOR POOL</div><h2>不是每次重新找人，<br/>而是慢慢建立品牌自己的<br/>嚴選創作者網絡。</h2><div className="actions"><BrandCTA>建立品牌嚴選創作者網絡</BrandCTA></div></div><div><p>把合作記憶留下來。分類、追蹤與回顧，讓每次選人都有累積。</p><CreatorPool/></div></div></section>

<section className="section" id="get-started"><div className="wrap"><AudienceCTA/></div></section><section className="section" id="faq"><div className="wrap faq-layout"><div><div className="eyebrow">FREQUENTLY ASKED QUESTIONS</div><h2>品牌第一次合作，<br/>也可以很簡單。</h2><p className="lead">從第一份需求，到第一場合作，<br/>先把你在意的問題說清楚。</p></div><FAQAccordion/></div></section>
</main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@graph":[{"@type":"Organization",name:"STEP1NE MATCH",logo:siteConfig.url+"/brand/logo-horizontal.png",url:siteConfig.url},{"@type":"WebSite",name:"STEP1NE MATCH KOC / KOL 品牌媒合",url:siteConfig.url,inLanguage:"zh-Hant"}]})}}/></>}
