import {ArrowRight,Check,Search,ShieldCheck,Users,ChartNoAxesCombined,Target,RefreshCw} from "lucide-react";
import {Header,BrandCTA,HeroMatchingPreview,FAQAccordion,CreatorPool} from "@/components/site-interactions";
import Link from "@/components/plain-link";
import {BrandLogo} from "@/components/brand-logo";
import {siteConfig} from "@/lib/site-config";
export function Footer(){return <footer className="footer"><div className="wrap"><div className="footer-grid"><div><Link className="brand-home" href="/" aria-label="STEP1NE MATCH 首頁"><BrandLogo footer/></Link><p>AI 精準媒合 × 真人顧問<br/>讓品牌與創作者，找到更好的合作。</p></div><div className="footer-links"><Link href="/#services">品牌合作</Link><Link href="/#ai-matching">AI 精準媒合</Link><Link href="/#workflow">合作流程</Link><Link href="/creators">KOC / KOL 加入</Link><Link href="/#faq">常見問題</Link><Link href="/brand-brief">聯絡顧問</Link></div></div><div className="copyright"><span>© 2026 STEP1NE MATCH. All rights reserved.</span><span>品牌合作媒合平台 · 網站預覽版</span></div></div></footer>}
const capabilities=[{icon:Search,title:"AI 人才探索",text:"從既有人才池與可取得的公開資訊，探索符合需求的合作人選。"},{icon:Target,title:"AI 契合度分析",text:"比對品牌、受眾、內容與平台需求，整理值得推薦的原因。"},{icon:ShieldCheck,title:"Creator 數據驗證",text:"結合已提供的 Insights、代表作品與合作紀錄，建立判斷依據。"},{icon:Users,title:"Human Review",text:"AI 協助縮小範圍，最終合作判斷由專業顧問人工審核。"}];
export default function Home(){return <><Header/><main id="main"><section className="hero"><div className="wrap"><div className="hero-grid"><div><div className="eyebrow">AI-POWERED KOC / KOL MATCHING PLATFORM</div><h1>AI 精準媒合，<br/>找到真正能為品牌<br/><span className="gradient">帶來成果</span>的 KOC / KOL</h1><p className="lead">不只看粉絲數，而是綜合受眾、內容風格、平台表現與歷史合作數據，從人選媒合、合作執行到成效追蹤，一站完成。</p><div className="actions"><BrandCTA/><Link className="btn secondary" href="#workflow">了解合作流程<ArrowRight size={17}/></Link></div><Link className="textlink" href={siteConfig.creatorJoinUrl}>我是 KOC / KOL → 加入合作人才池</Link></div><HeroMatchingPreview/></div><div className="trust">{[[Target,"AI 精準媒合"],[ShieldCheck,"Creator 數據驗證"],[Users,"真人顧問把關"],[ChartNoAxesCombined,"Campaign 成效追蹤"]].map(([Icon,label])=>{const I=Icon as typeof Target;return <span key={String(label)}><I/>{String(label)}</span>})}</div></div></section>
<section className="section soft"><div className="wrap split"><div><div className="eyebrow">THE PROBLEM</div><h2>粉絲數，<br/>不等於適合度。</h2><p className="lead">找 KOC / KOL，不該只是從粉絲最多的人開始挑。</p><div className="actions"><Link className="btn" href="#ai-matching">看看 AI 如何媒合<ArrowRight size={17}/></Link></div></div><div><div className="comparison"><div className="compare-col"><h3>傳統找人</h3><ul>{["看粉絲數","看版面印象","人工搜尋","一個個私訊","發布後資料散落"].map(t=><li key={t}><Search size={15}/>{t}</li>)}</ul></div><div className="compare-col best"><h3>AI 精準媒合</h3><ul>{["品牌需求分析","目標客群比對","內容語意分析","平台表現","歷史合作紀錄","顧問人工審核"].map(t=><li key={t}><Check size={15}/>{t}</li>)}</ul></div></div><p className="quote">AI 先找出值得看的那群人，再由專業顧問完成最後判斷。</p></div></div></section>
<section className="section" id="ai-matching"><div className="wrap"><div className="eyebrow">AI CAPABILITIES</div><div className="section-top"><div><h2>不只找得到人，<br/>更要知道「為什麼適合」。</h2><p className="lead">AI 精準媒合，是將品牌需求轉成多維度條件，結合 Creator 資料與實際合作紀錄，協助顧問更快找出高契合候選人。</p></div><Link className="btn secondary" href="#dimensions">了解媒合維度<ArrowRight size={17}/></Link></div><div className="grid4">{capabilities.map((c,i)=><article className="cap" key={c.title}><small>0{i+1}</small><span className="icon"><c.icon size={22}/></span><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></div></section>
<section className="journey" id="services"><div className="wrap"><div className="section-top"><div><div className="eyebrow">FROM BRIEF TO REAL IMPACT</div><h2>從找人，到合作真正落地。</h2><p className="lead">不是丟一份名單給品牌，而是把 KOC / KOL 合作流程一路往前推進。</p></div><BrandCTA>提交品牌合作需求</BrandCTA></div><div className="grid4">{[["需求拆解","釐清產品、目標客群、預算與時程。"],["AI 精準媒合","多維度分析，再由顧問把關推薦。"],["合作執行","確認報價、檔期、內容與發布進度。"],["成效回收","整理可驗證結果，提出下一波建議。"]].map(([t,d],i)=><div className="stage" key={t}><b>0{i+1}</b><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section className="section" id="dimensions"><div className="wrap split"><div><div className="eyebrow">CREATOR INTELLIGENCE PROFILE</div><h2>我們看的，<br/>不只有粉絲數。</h2><p className="lead">每個 Creator 都有自己的合作輪廓，而不是只剩一個 Followers 數字。</p><p className="quote">受眾是否吻合？內容是否自然？<br/>合作資料是否足以支持推薦？</p></div><div className="dimensions">{[["受眾契合","Audience Fit"],["內容契合","Content Fit"],["平台契合","Platform Fit"],["互動品質","Engagement Quality"],["歷史表現","Historical Performance"],["商業經驗","Commercial Experience"],["合作可靠度","Collaboration Reliability"],["品牌安全","Brand Safety"],["資料可信度","Data Confidence"]].map(([t,e])=><div className="dimension" key={t}><b>{t}</b><span>{e}</span></div>)}</div></div></section>
<section className="section soft"><div className="wrap split"><div className="verification"><div className="panel-heading"><strong>Creator 資料檢核</strong><span className="badge">示意畫面</span></div>{[["社群帳號・代表作品","公開 / 本人提供"],["Audience・Account Insights","需本人提供"],["Content Insights","依可取得資料"],["商業合作案例・Rate Card","需確認"],["Data Freshness","記錄更新日期"],["Data Confidence","標示資料來源"]].map(([l,r])=><div className="verify-row" key={l}><b>{l}</b><span>{r}</span></div>)}<p className="note">依公開資訊、Creator 提交資料與可用權限驗證。</p></div><div><div className="eyebrow">CREATOR DATA VERIFICATION</div><h2>公開數字，<br/>只是第一層。</h2><p className="lead">值得推薦的 Creator，我們會進一步建立可驗證的合作資料。從代表作品到受眾洞察，把「看起來適合」變成有依據的判斷。</p><p className="quote">沒有取得的資料，就清楚標示。<br/>不把未知，當成已驗證。</p></div></div></section>
<section className="section" id="workflow"><div className="wrap"><div className="eyebrow">COLLABORATION WORKFLOW</div><h2>從媒合到發布，每一步都有人追。</h2><p className="lead">品牌不用自己一個個私訊、一個個記進度。</p><div className="timeline">{["品牌提交需求","AI 初步媒合","顧問人工審核","品牌挑選","Creator 邀約與條件確認","內容與發布管理","成效回收","下一波建議"].map((t,i)=><div className="step" key={t}><b>STEP 0{i+1}</b><h3>{t}</h3></div>)}</div></div></section>
<section className="section soft" id="results"><div className="wrap"><div className="eyebrow">CAMPAIGN PERFORMANCE</div><h2>最後看的，不是「找了幾個人」，<br/>而是「做出了什麼結果」。</h2><p className="lead">把分散的數據整理在一起，看見不同人選、平台與內容角度的合作表現。</p><div className="dashboard"><div className="panel-heading"><strong>Campaign 成效總覽</strong><span className="badge">示意 Dashboard・非客戶實績</span></div><div className="stats">{[["128K","觸及 Reach"],["246K","觀看 Views"],["8,420","互動 Engagement"],["1,260","點擊 Clicks"]].map(([n,l])=><div className="stat" key={l}><span>{l}</span><strong>{n}</strong></div>)}</div><div className="dashboard-bottom"><div><div className="bars" aria-label="示意圖：不同內容的觀看表現"><i style={{height:"34%"}}/><i style={{height:"58%"}}/><i style={{height:"46%"}}/><i style={{height:"77%"}}/><i style={{height:"64%"}}/><i style={{height:"94%"}}/><i style={{height:"83%"}}/></div><div className="bar-label"><span>內容表現比較</span><span>示意數據</span></div></div><div className="insight"><strong>不只回收數字，也整理下一步。</strong>比較平台分布、Creator 表現與內容角度，辨識值得延續的合作方式。<div className="chips"><span className="chip">Platform distribution</span><span className="chip">Content insights</span></div></div></div></div><p className="note">可追蹤指標依平台權限、追蹤設定與 Creator 提供資料而定。圖中數值僅展示報告形式。</p></div></section>
<section className="section"><div className="wrap split"><div><div className="eyebrow">PERFORMANCE LEARNING LOOP</div><h2>每一次合作，<br/>都讓下一次媒合更準。</h2></div><div><p>Creator 的真實合作表現、內容成果與品牌回饋持續回寫，讓下一次媒合不再從零開始。</p><div className="loop">{["媒合","合作","成效","回寫"].map((t,i)=><span key={t}>{i+1} · {t}</span>)}<RefreshCw/><span>下一次媒合</span></div></div></div></section>
<section className="section soft"><div className="wrap split"><div><div className="eyebrow">YOUR BRAND, YOUR CREATOR POOL</div><h2>不是每次重新找人，<br/>而是慢慢建立品牌自己的<br/>Creator 合作池。</h2><div className="actions"><BrandCTA>建立品牌 Creator Pool</BrandCTA></div></div><div><p>把合作記憶留下來。分類、追蹤與回顧，讓每次選人都有累積。</p><CreatorPool/></div></div></section>
<section className="section" id="creator-join"><div className="wrap"><div className="creator-cta"><div><div className="eyebrow">FOR CREATORS</div><h2>你是 KOC / KOL 嗎？<br/>讓適合你的品牌合作找到你。</h2><p className="lead">加入合作人才池，建立 Creator Profile，接收適合你的品牌合作機會。</p><div className="actions"><Link className="btn secondary" href="/creators">加入 KOC / KOL 合作人才池<ArrowRight size={17}/></Link></div></div><div className="creator-benefits">{["建立合作資料","接收品牌邀請","自主確認合作","累積合作紀錄"].map(t=><span key={t}><Check size={19} style={{marginBottom:9,color:"#6877ca"}}/>{t}</span>)}</div></div></div></section>
<section className="section" id="faq"><div className="wrap faq-layout"><div><div className="eyebrow">FREQUENTLY ASKED QUESTIONS</div><h2>品牌第一次合作，<br/>也可以很簡單。</h2><p className="lead">從第一份需求，到第一場合作，<br/>先把你在意的問題說清楚。</p></div><FAQAccordion/></div></section>
<section className="final"><div className="wrap"><div className="eyebrow">BETTER CREATORS. BRIGHTER BRANDS.</div><h2>準備找到真正適合品牌的<br/>KOC / KOL 了嗎？</h2><p>告訴我們你的品牌、產品與推廣目標，開始第一輪 AI 精準媒合。</p><BrandCTA/><p className="note">已經有 Brand Deck？可以直接提供，我們會先整理既有資訊，再確認真正缺少的內容。</p></div></section></main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@graph":[{"@type":"Organization",name:"STEP1NE MATCH",logo:siteConfig.url+"/brand/logo-horizontal.png",url:siteConfig.url},{"@type":"WebSite",name:"STEP1NE MATCH KOC / KOL 品牌媒合",url:siteConfig.url,inLanguage:"zh-Hant"}]})}}/></>}
