"use client";
import {useEffect,useState,useSyncExternalStore,useRef} from "react";
import {ArrowRight,ChevronLeft,ChevronRight,Pause,Play,Menu,X,Sparkles,BriefcaseBusiness} from "lucide-react";
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from "@/components/ui/accordion";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import Link from "@/components/plain-link";
import {BrandLogo} from "@/components/brand-logo";
import {siteConfig} from "@/lib/site-config";
export const creators=[{name:"Claire",handle:"@claire.daily",tag:"美妝保養",score:92,fit:"受眾契合・真實體驗分享",position:"74.2% 9.8%"},{name:"Yuna",handle:"@yuna.style",tag:"生活風格",score:87,fit:"內容契合・日常情境提案",position:"74.2% 30.9%"},{name:"Hsu",handle:"@hsu.foodie",tag:"美食旅遊",score:83,fit:"平台契合・短影音敘事",position:"74.2% 52.4%"}];
export function Portrait({index=0}:{index?:number}){return <span role="img" aria-label={`${creators[index].name} 虛構創作者示意肖像`} className="portrait" style={{display:"block",flexShrink:0,backgroundImage:"url(/matching-reference.png)",backgroundSize:"1250% auto",backgroundPosition:creators[index].position}}/>}
export function AnimatedNumber({value,suffix=""}:{value:number;suffix?:string}){const[count,setCount]=useState(value);const ref=useRef<HTMLSpanElement>(null);useEffect(()=>{if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;let frame=0;const observer=new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)return;observer.disconnect();const start=performance.now();const animate=(now:number)=>{const t=Math.min((now-start)/850,1);setCount(Math.round(value*(1-Math.pow(1-t,3))));if(t<1)frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate)},{threshold:0.4});if(ref.current)observer.observe(ref.current);return()=>{observer.disconnect();cancelAnimationFrame(frame)}},[value]);return <span ref={ref} aria-label={value+suffix}>{count.toLocaleString("en-US")}{suffix}</span>}
export function BrandCTA({children="開始品牌媒合",secondary=false}:{children?:React.ReactNode;secondary?:boolean}){return <Link className={`btn${secondary?" secondary":""}`} href={siteConfig.brandBriefUrl}>{children}<ArrowRight size={17}/></Link>}
export function Header(){const[open,setOpen]=useState(false);const links=[["品牌合作","/#services"],["AI 精準媒合","/#ai-matching"],["如何運作","/#workflow"],["合作成效","/#results"],["KOC / KOL 加入",siteConfig.creatorJoinUrl]];return <header className="header"><Link className="skip" href="#main">跳至主要內容</Link><div className="wrap topbar"><Link href="/" className="brand-home" aria-label="STEP1NE MATCH 首頁"><BrandLogo/></Link><nav className="nav" aria-label="主要導覽">{links.map(([label,href])=><Link key={label} href={href}>{label}</Link>)}</nav><BrandCTA/><button aria-label={open?"關閉選單":"開啟選單"} aria-expanded={open} aria-controls="mobile-menu" className="menu" onClick={()=>setOpen(!open)}>{open?<X size={22}/>:<Menu size={22}/>}</button></div>{open&&<nav id="mobile-menu" className="mobile-nav" aria-label="手機導覽">{links.map(([label,href])=><Link key={label} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}</nav>}</header>}
function subscribeMotion(callback:()=>void){const m=matchMedia("(prefers-reduced-motion: reduce)");m.addEventListener("change",callback);return()=>m.removeEventListener("change",callback)}
export function HeroMatchingPreview(){const[active,setActive]=useState(0);const[paused,setPaused]=useState(false);const reduced=useSyncExternalStore(subscribeMotion,()=>matchMedia("(prefers-reduced-motion: reduce)").matches,()=>true);useEffect(()=>{if(paused||reduced)return;const t=setInterval(()=>setActive(a=>(a+1)%3),5000);return()=>clearInterval(t)},[paused,reduced]);function change(n:number){setPaused(true);setActive((n+3)%3)}return <div className="hero-visual" aria-label="AI 媒合示意" onTouchStart={e=>{e.currentTarget.dataset.start=String(e.touches[0].clientX)}} onTouchEnd={e=>{const delta=e.changedTouches[0].clientX-Number(e.currentTarget.dataset.start);if(Math.abs(delta)>50)change(active+(delta<0?1:-1))}}><div className="brief"><strong><BriefcaseBusiness size={19} color="#6976e4"/>品牌需求 <span className="badge" style={{marginLeft:"auto"}}>示意</span></strong><div className="chips">{["美妝保養","台灣受眾","Instagram","產品開箱"].map(x=><span className="chip" key={x}>{x}</span>)}</div></div><div className="match-label"><span style={{display:"flex",gap:8,alignItems:"center"}}><Sparkles size={15}/>AI 多維度契合分析</span><span>AI + HUMAN REVIEW</span></div>{creators.map((c,i)=><button key={c.name} className={`creator-card ${active===i?"active":""}`} aria-pressed={active===i} aria-label={`查看 ${c.name} 媒合示意`} onClick={()=>change(i)}><Portrait index={i}/><div><span className="chip">{c.tag}</span><div className="creator-name">{c.handle}</div><div className="creator-meta">{c.fit}</div></div><span className="score"><strong><AnimatedNumber value={c.score} suffix="%"/></strong><small>契合示意</small></span></button>)}<div className="visual-foot"><span>虛構人選與分數，非實際推薦結果</span><div className="round-controls"><button aria-label="上一位創作者" onClick={()=>change(active-1)}><ChevronLeft size={15}/></button><button aria-label={paused?"播放切換":"暫停切換"} onClick={()=>setPaused(!paused)}>{paused?<Play size={13}/>:<Pause size={13}/>}</button><button aria-label="下一位創作者" onClick={()=>change(active+1)}><ChevronRight size={15}/></button></div></div></div>}
const questions=[["一定要先有 KOC/KOL 名單嗎？","不需要。提供品牌、產品、目標客群與推廣目標後，顧問會先整理媒合條件，再協助探索適合的人選。"],["可以只找 KOC 嗎？","可以。合作人選會依推廣目標、受眾、內容形式與預算規劃，不一定要搭配 KOL。"],["你們只提供名單嗎？","不只提供名單。我們協助需求拆解、人選媒合、顧問審核、邀約與條件確認、內容發布追蹤及成效回收，實際服務範圍會於合作前確認。"],["Creator 合作費怎麼確認？","依 Creator 報價、內容形式、發布平台、授權範圍、檔期與其他合作條件確認。顧問會整理費用與服務範圍，由品牌確認後再推進。"],["可以只做特定平台嗎？","可以先指定希望合作的平台，例如 Instagram、Threads 或 YouTube；顧問會依目標與人選資料，確認適合的內容形式與可執行範圍。"],["品牌已經有 Brief，還需要重新填資料嗎？","不需要重做完整 Brief。可以先整理既有 Brand Deck 或需求文件，由顧問確認尚缺的產品、受眾、預算與時程資訊。"],["怎麼追蹤合作後的成效？","合作前先確認指標與可取得的資料，發布後整理觸及、觀看、互動與可追蹤的點擊等結果。平台權限與 Creator 提供資料會影響可驗證的範圍。"]];
export function FAQAccordion(){return <Accordion type="single" collapsible className="faq">{questions.map(([q,a],i)=><AccordionItem key={q} value={String(i)}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent forceMount>{a}</AccordionContent></AccordionItem>)}</Accordion>}
export function CreatorPool(){const states=[{name:"值得再合作",text:"保留契合品牌、執行順利的人選，下一次合作可以從熟悉的夥伴開始。",index:0},{name:"下一波測試",text:"為新的產品、內容角度或平台，預留值得嘗試的合作人選。",index:1},{name:"待觀察",text:"補齊受眾與作品資料，再由顧問評估是否適合下一輪合作。",index:2},{name:"暫不推薦",text:"記錄本次不適合的原因，避免重複邀約與無效溝通。",index:1}];return <Tabs defaultValue="值得再合作" className="pool"><TabsList aria-label="合作池分類">{states.map(s=><TabsTrigger key={s.name} value={s.name}>{s.name}</TabsTrigger>)}</TabsList>{states.map(s=><TabsContent key={s.name} value={s.name}><div className="pool-content"><Portrait index={s.index}/><div><span className="badge">合作池示意</span><p>{s.text}</p></div></div></TabsContent>)}</Tabs>}
export function BriefForm({creator=false}:{creator?:boolean}){const[summary,setSummary]=useState("");const[message,setMessage]=useState("");useEffect(()=>{type Tool={name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>Promise<unknown>};const ctx=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!ctx)return;const abort=new AbortController();Promise.resolve(ctx.registerTool({name:creator?"prepare_creator_summary":"prepare_brand_brief_summary",title:creator?"整理創作者合作摘要":"整理品牌需求摘要",description:"Prepare a visible, copyable summary only. Does not send or store data.",inputSchema:{type:"object",properties:{name:{type:"string",minLength:1,maxLength:100},details:{type:"string",minLength:1,maxLength:5000}},required:["name","details"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=="object")throw Error("Invalid input");const d=input as Record<string,unknown>;if(typeof d.name!=="string"||!d.name.trim()||d.name.length>100||typeof d.details!=="string"||!d.details.trim()||d.details.length>5000||Object.keys(d).some(k=>!["name","details"].includes(k)))throw Error("Name and details are required within length limits");setSummary(d.name+"\n"+d.details);setMessage("摘要已整理完成。尚未傳送，請複製後提供給你的顧問。");await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return {status:"prepared",sent:false};}}, {signal:abort.signal})).catch(()=>{});return()=>abort.abort()},[creator]);return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const lines=Array.from(f.entries()).map(([k,v])=>`${k}：${v}`).join("\n");setSummary(lines);setMessage("摘要已整理完成。尚未傳送，請複製後提供給你的顧問。");}}><div className="notice">目前可先整理{creator?"合作資料":"品牌需求"}摘要。聯絡入口尚未開放，這份表單不會傳送或儲存你的資料。</div><label className="field">{creator?"創作者名稱":"品牌名稱"}<input name={creator?"創作者名稱":"品牌名稱"} required maxLength={100} autoComplete="organization"/></label><label className="field">{creator?"社群帳號連結":"產品 / 服務"}<input name={creator?"社群帳號":"產品服務"} type={creator?"url":"text"} required maxLength={300}/></label><label className="field">{creator?"擅長的內容與合作形式":"推廣目標與目標客群"}<textarea name={creator?"內容與形式":"目標與客群"} required maxLength={2000}/></label><label className="field">{creator?"可合作檔期與補充資訊":"預算、時程與既有 Brief 摘要"}<textarea name="補充資訊" maxLength={3000}/></label><button className="btn" style={{marginTop:25}} type="submit">整理{creator?"合作資料":"品牌需求"}摘要 <ArrowRight size={17}/></button>{summary&&<div className="notice"><p role="status">{message}</p><label className="field">可複製摘要<textarea readOnly value={summary} style={{minHeight:180}}/></label><button type="button" className="btn secondary" onClick={async()=>{try{await navigator.clipboard.writeText(summary);setMessage("摘要已複製。你可以貼給顧問繼續討論。")}catch{setMessage("請選取上方摘要文字，手動複製。")}}}>複製摘要</button></div>}</form>}
